FROM mhart/alpine-node:14.16.1
# We first copy the package.json file and the binaries stored in the source repository.
# use changes to package.json to force Docker not to use the cache
# when we change our application's nodejs dependencies:
RUN npm -v
COPY package.json /app/package.json
RUN cd /app && npm install -S --unsafe-perm=true --allow-root
